/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGamedayRouteImport } from './routes/_authenticated/gameday'
import { Route as AuthenticatedManagerHubRouteImport } from './routes/_authenticated/manager-hub'
import { Route as AuthenticatedProjectionsRouteImport } from './routes/_authenticated/projections'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedLeagueLeagueIdRouteImport } from './routes/_authenticated/league.$leagueId'
import { Route as ApiPublicCronLiveScoringRouteImport } from './routes/api/public/cron/live-scoring'
import { Route as ApiPublicCronTradeValuesRouteImport } from './routes/api/public/cron/trade-values'
import { Route as ApiPublicCronTradeValuesIrRouteImport } from './routes/api/public/cron/trade-values-ir'
import { Route as ApiPublicYahooCallbackRouteImport } from './routes/api/public/yahoo/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamedayRoute = AuthenticatedGamedayRouteImport.update({
  id: '/gameday',
  path: '/gameday',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerHubRoute = AuthenticatedManagerHubRouteImport.update({
  id: '/manager-hub',
  path: '/manager-hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectionsRoute =
  AuthenticatedProjectionsRouteImport.update({
    id: '/projections',
    path: '/projections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueLeagueIdRoute =
  AuthenticatedLeagueLeagueIdRouteImport.update({
    id: '/league/$leagueId',
    path: '/league/$leagueId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronLiveScoringRoute =
  ApiPublicCronLiveScoringRouteImport.update({
    id: '/api/public/cron/live-scoring',
    path: '/api/public/cron/live-scoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTradeValuesRoute =
  ApiPublicCronTradeValuesRouteImport.update({
    id: '/api/public/cron/trade-values',
    path: '/api/public/cron/trade-values',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTradeValuesIrRoute =
  ApiPublicCronTradeValuesIrRouteImport.update({
    id: '/api/public/cron/trade-values-ir',
    path: '/api/public/cron/trade-values-ir',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicYahooCallbackRoute = ApiPublicYahooCallbackRouteImport.update({
  id: '/api/public/yahoo/callback',
  path: '/api/public/yahoo/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gameday': typeof AuthenticatedGamedayRoute
  '/manager-hub': typeof AuthenticatedManagerHubRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRoute
  '/api/public/cron/live-scoring': typeof ApiPublicCronLiveScoringRoute
  '/api/public/cron/trade-values': typeof ApiPublicCronTradeValuesRoute
  '/api/public/cron/trade-values-ir': typeof ApiPublicCronTradeValuesIrRoute
  '/api/public/yahoo/callback': typeof ApiPublicYahooCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gameday': typeof AuthenticatedGamedayRoute
  '/manager-hub': typeof AuthenticatedManagerHubRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRoute
  '/api/public/cron/live-scoring': typeof ApiPublicCronLiveScoringRoute
  '/api/public/cron/trade-values': typeof ApiPublicCronTradeValuesRoute
  '/api/public/cron/trade-values-ir': typeof ApiPublicCronTradeValuesIrRoute
  '/api/public/yahoo/callback': typeof ApiPublicYahooCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gameday': typeof AuthenticatedGamedayRoute
  '/_authenticated/manager-hub': typeof AuthenticatedManagerHubRoute
  '/_authenticated/projections': typeof AuthenticatedProjectionsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRoute
  '/api/public/cron/live-scoring': typeof ApiPublicCronLiveScoringRoute
  '/api/public/cron/trade-values': typeof ApiPublicCronTradeValuesRoute
  '/api/public/cron/trade-values-ir': typeof ApiPublicCronTradeValuesIrRoute
  '/api/public/yahoo/callback': typeof ApiPublicYahooCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect'
    | '/dashboard'
    | '/gameday'
    | '/manager-hub'
    | '/projections'
    | '/trades'
    | '/league/$leagueId'
    | '/api/public/cron/live-scoring'
    | '/api/public/cron/trade-values'
    | '/api/public/cron/trade-values-ir'
    | '/api/public/yahoo/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/dashboard'
    | '/gameday'
    | '/manager-hub'
    | '/projections'
    | '/trades'
    | '/league/$leagueId'
    | '/api/public/cron/live-scoring'
    | '/api/public/cron/trade-values'
    | '/api/public/cron/trade-values-ir'
    | '/api/public/yahoo/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/connect'
    | '/_authenticated/dashboard'
    | '/_authenticated/gameday'
    | '/_authenticated/manager-hub'
    | '/_authenticated/projections'
    | '/_authenticated/trades'
    | '/_authenticated/league/$leagueId'
    | '/api/public/cron/live-scoring'
    | '/api/public/cron/trade-values'
    | '/api/public/cron/trade-values-ir'
    | '/api/public/yahoo/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronLiveScoringRoute: typeof ApiPublicCronLiveScoringRoute
  ApiPublicCronTradeValuesRoute: typeof ApiPublicCronTradeValuesRoute
  ApiPublicCronTradeValuesIrRoute: typeof ApiPublicCronTradeValuesIrRoute
  ApiPublicYahooCallbackRoute: typeof ApiPublicYahooCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gameday': {
      id: '/_authenticated/gameday'
      path: '/gameday'
      fullPath: '/gameday'
      preLoaderRoute: typeof AuthenticatedGamedayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager-hub': {
      id: '/_authenticated/manager-hub'
      path: '/manager-hub'
      fullPath: '/manager-hub'
      preLoaderRoute: typeof AuthenticatedManagerHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projections': {
      id: '/_authenticated/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof AuthenticatedProjectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$leagueId': {
      id: '/_authenticated/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/live-scoring': {
      id: '/api/public/cron/live-scoring'
      path: '/api/public/cron/live-scoring'
      fullPath: '/api/public/cron/live-scoring'
      preLoaderRoute: typeof ApiPublicCronLiveScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/trade-values': {
      id: '/api/public/cron/trade-values'
      path: '/api/public/cron/trade-values'
      fullPath: '/api/public/cron/trade-values'
      preLoaderRoute: typeof ApiPublicCronTradeValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/trade-values-ir': {
      id: '/api/public/cron/trade-values-ir'
      path: '/api/public/cron/trade-values-ir'
      fullPath: '/api/public/cron/trade-values-ir'
      preLoaderRoute: typeof ApiPublicCronTradeValuesIrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yahoo/callback': {
      id: '/api/public/yahoo/callback'
      path: '/api/public/yahoo/callback'
      fullPath: '/api/public/yahoo/callback'
      preLoaderRoute: typeof ApiPublicYahooCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGamedayRoute: typeof AuthenticatedGamedayRoute
  AuthenticatedManagerHubRoute: typeof AuthenticatedManagerHubRoute
  AuthenticatedProjectionsRoute: typeof AuthenticatedProjectionsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedLeagueLeagueIdRoute: typeof AuthenticatedLeagueLeagueIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGamedayRoute: AuthenticatedGamedayRoute,
  AuthenticatedManagerHubRoute: AuthenticatedManagerHubRoute,
  AuthenticatedProjectionsRoute: AuthenticatedProjectionsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedLeagueLeagueIdRoute: AuthenticatedLeagueLeagueIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronLiveScoringRoute: ApiPublicCronLiveScoringRoute,
  ApiPublicCronTradeValuesRoute: ApiPublicCronTradeValuesRoute,
  ApiPublicCronTradeValuesIrRoute: ApiPublicCronTradeValuesIrRoute,
  ApiPublicYahooCallbackRoute: ApiPublicYahooCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
