/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedGamedayRouteImport } from './routes/_authenticated/gameday'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedLineupCheckRouteImport } from './routes/_authenticated/lineup-check'
import { Route as AuthenticatedManagerHubRouteImport } from './routes/_authenticated/manager-hub'
import { Route as AuthenticatedProjectionsRouteImport } from './routes/_authenticated/projections'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedThisWeekRouteImport } from './routes/_authenticated/this-week'
import { Route as AuthenticatedTradeDeskRouteImport } from './routes/_authenticated/trade-desk'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as AuthenticatedWaiversRouteImport } from './routes/_authenticated/waivers'
import { Route as AuthenticatedLeagueLeagueIdRouteImport } from './routes/_authenticated/league.$leagueId'
import { Route as ApiPublicCronInactivesRouteImport } from './routes/api/public/cron/inactives'
import { Route as ApiPublicCronLiveScoringRouteImport } from './routes/api/public/cron/live-scoring'
import { Route as ApiPublicCronTradeValuesRouteImport } from './routes/api/public/cron/trade-values'
import { Route as ApiPublicCronTradeValuesIrRouteImport } from './routes/api/public/cron/trade-values-ir'
import { Route as ApiPublicYahooCallbackRouteImport } from './routes/api/public/yahoo/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamedayRoute = AuthenticatedGamedayRouteImport.update({
  id: '/gameday',
  path: '/gameday',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLineupCheckRoute =
  AuthenticatedLineupCheckRouteImport.update({
    id: '/lineup-check',
    path: '/lineup-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerHubRoute = AuthenticatedManagerHubRouteImport.update({
  id: '/manager-hub',
  path: '/manager-hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectionsRoute =
  AuthenticatedProjectionsRouteImport.update({
    id: '/projections',
    path: '/projections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThisWeekRoute = AuthenticatedThisWeekRouteImport.update({
  id: '/this-week',
  path: '/this-week',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradeDeskRoute = AuthenticatedTradeDeskRouteImport.update({
  id: '/trade-desk',
  path: '/trade-desk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaiversRoute = AuthenticatedWaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueLeagueIdRoute =
  AuthenticatedLeagueLeagueIdRouteImport.update({
    id: '/league/$leagueId',
    path: '/league/$leagueId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronInactivesRoute = ApiPublicCronInactivesRouteImport.update({
  id: '/api/public/cron/inactives',
  path: '/api/public/cron/inactives',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronLiveScoringRoute =
  ApiPublicCronLiveScoringRouteImport.update({
    id: '/api/public/cron/live-scoring',
    path: '/api/public/cron/live-scoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTradeValuesRoute =
  ApiPublicCronTradeValuesRouteImport.update({
    id: '/api/public/cron/trade-values',
    path: '/api/public/cron/trade-values',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronTradeValuesIrRoute =
  ApiPublicCronTradeValuesIrRouteImport.update({
    id: '/api/public/cron/trade-values-ir',
    path: '/api/public/cron/trade-values-ir',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicYahooCallbackRoute = ApiPublicYahooCallbackRouteImport.update({
  id: '/api/public/yahoo/callback',
  path: '/api/public/yahoo/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/gameday': typeof AuthenticatedGamedayRoute
  '/games': typeof AuthenticatedGamesRoute
  '/lineup-check': typeof AuthenticatedLineupCheckRoute
  '/manager-hub': typeof AuthenticatedManagerHubRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/this-week': typeof AuthenticatedThisWeekRoute
  '/trade-desk': typeof AuthenticatedTradeDeskRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/tv': typeof AuthenticatedTvRoute
  '/waivers': typeof AuthenticatedWaiversRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRoute
  '/api/public/cron/inactives': typeof ApiPublicCronInactivesRoute
  '/api/public/cron/live-scoring': typeof ApiPublicCronLiveScoringRoute
  '/api/public/cron/trade-values': typeof ApiPublicCronTradeValuesRoute
  '/api/public/cron/trade-values-ir': typeof ApiPublicCronTradeValuesIrRoute
  '/api/public/yahoo/callback': typeof ApiPublicYahooCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/gameday': typeof AuthenticatedGamedayRoute
  '/games': typeof AuthenticatedGamesRoute
  '/lineup-check': typeof AuthenticatedLineupCheckRoute
  '/manager-hub': typeof AuthenticatedManagerHubRoute
  '/projections': typeof AuthenticatedProjectionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/this-week': typeof AuthenticatedThisWeekRoute
  '/trade-desk': typeof AuthenticatedTradeDeskRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/tv': typeof AuthenticatedTvRoute
  '/waivers': typeof AuthenticatedWaiversRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRoute
  '/api/public/cron/inactives': typeof ApiPublicCronInactivesRoute
  '/api/public/cron/live-scoring': typeof ApiPublicCronLiveScoringRoute
  '/api/public/cron/trade-values': typeof ApiPublicCronTradeValuesRoute
  '/api/public/cron/trade-values-ir': typeof ApiPublicCronTradeValuesIrRoute
  '/api/public/yahoo/callback': typeof ApiPublicYahooCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/gameday': typeof AuthenticatedGamedayRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/lineup-check': typeof AuthenticatedLineupCheckRoute
  '/_authenticated/manager-hub': typeof AuthenticatedManagerHubRoute
  '/_authenticated/projections': typeof AuthenticatedProjectionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/this-week': typeof AuthenticatedThisWeekRoute
  '/_authenticated/trade-desk': typeof AuthenticatedTradeDeskRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/_authenticated/waivers': typeof AuthenticatedWaiversRoute
  '/_authenticated/league/$leagueId': typeof AuthenticatedLeagueLeagueIdRoute
  '/api/public/cron/inactives': typeof ApiPublicCronInactivesRoute
  '/api/public/cron/live-scoring': typeof ApiPublicCronLiveScoringRoute
  '/api/public/cron/trade-values': typeof ApiPublicCronTradeValuesRoute
  '/api/public/cron/trade-values-ir': typeof ApiPublicCronTradeValuesIrRoute
  '/api/public/yahoo/callback': typeof ApiPublicYahooCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/connect'
    | '/gameday'
    | '/games'
    | '/lineup-check'
    | '/manager-hub'
    | '/projections'
    | '/settings'
    | '/this-week'
    | '/trade-desk'
    | '/trades'
    | '/tv'
    | '/waivers'
    | '/league/$leagueId'
    | '/api/public/cron/inactives'
    | '/api/public/cron/live-scoring'
    | '/api/public/cron/trade-values'
    | '/api/public/cron/trade-values-ir'
    | '/api/public/yahoo/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/connect'
    | '/gameday'
    | '/games'
    | '/lineup-check'
    | '/manager-hub'
    | '/projections'
    | '/settings'
    | '/this-week'
    | '/trade-desk'
    | '/trades'
    | '/tv'
    | '/waivers'
    | '/league/$leagueId'
    | '/api/public/cron/inactives'
    | '/api/public/cron/live-scoring'
    | '/api/public/cron/trade-values'
    | '/api/public/cron/trade-values-ir'
    | '/api/public/yahoo/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/connect'
    | '/_authenticated/gameday'
    | '/_authenticated/games'
    | '/_authenticated/lineup-check'
    | '/_authenticated/manager-hub'
    | '/_authenticated/projections'
    | '/_authenticated/settings'
    | '/_authenticated/this-week'
    | '/_authenticated/trade-desk'
    | '/_authenticated/trades'
    | '/_authenticated/tv'
    | '/_authenticated/waivers'
    | '/_authenticated/league/$leagueId'
    | '/api/public/cron/inactives'
    | '/api/public/cron/live-scoring'
    | '/api/public/cron/trade-values'
    | '/api/public/cron/trade-values-ir'
    | '/api/public/yahoo/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronInactivesRoute: typeof ApiPublicCronInactivesRoute
  ApiPublicCronLiveScoringRoute: typeof ApiPublicCronLiveScoringRoute
  ApiPublicCronTradeValuesRoute: typeof ApiPublicCronTradeValuesRoute
  ApiPublicCronTradeValuesIrRoute: typeof ApiPublicCronTradeValuesIrRoute
  ApiPublicYahooCallbackRoute: typeof ApiPublicYahooCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gameday': {
      id: '/_authenticated/gameday'
      path: '/gameday'
      fullPath: '/gameday'
      preLoaderRoute: typeof AuthenticatedGamedayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lineup-check': {
      id: '/_authenticated/lineup-check'
      path: '/lineup-check'
      fullPath: '/lineup-check'
      preLoaderRoute: typeof AuthenticatedLineupCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager-hub': {
      id: '/_authenticated/manager-hub'
      path: '/manager-hub'
      fullPath: '/manager-hub'
      preLoaderRoute: typeof AuthenticatedManagerHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projections': {
      id: '/_authenticated/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof AuthenticatedProjectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/this-week': {
      id: '/_authenticated/this-week'
      path: '/this-week'
      fullPath: '/this-week'
      preLoaderRoute: typeof AuthenticatedThisWeekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trade-desk': {
      id: '/_authenticated/trade-desk'
      path: '/trade-desk'
      fullPath: '/trade-desk'
      preLoaderRoute: typeof AuthenticatedTradeDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/waivers': {
      id: '/_authenticated/waivers'
      path: '/waivers'
      fullPath: '/waivers'
      preLoaderRoute: typeof AuthenticatedWaiversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$leagueId': {
      id: '/_authenticated/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/inactives': {
      id: '/api/public/cron/inactives'
      path: '/api/public/cron/inactives'
      fullPath: '/api/public/cron/inactives'
      preLoaderRoute: typeof ApiPublicCronInactivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/live-scoring': {
      id: '/api/public/cron/live-scoring'
      path: '/api/public/cron/live-scoring'
      fullPath: '/api/public/cron/live-scoring'
      preLoaderRoute: typeof ApiPublicCronLiveScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/trade-values': {
      id: '/api/public/cron/trade-values'
      path: '/api/public/cron/trade-values'
      fullPath: '/api/public/cron/trade-values'
      preLoaderRoute: typeof ApiPublicCronTradeValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/trade-values-ir': {
      id: '/api/public/cron/trade-values-ir'
      path: '/api/public/cron/trade-values-ir'
      fullPath: '/api/public/cron/trade-values-ir'
      preLoaderRoute: typeof ApiPublicCronTradeValuesIrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yahoo/callback': {
      id: '/api/public/yahoo/callback'
      path: '/api/public/yahoo/callback'
      fullPath: '/api/public/yahoo/callback'
      preLoaderRoute: typeof ApiPublicYahooCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedGamedayRoute: typeof AuthenticatedGamedayRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedLineupCheckRoute: typeof AuthenticatedLineupCheckRoute
  AuthenticatedManagerHubRoute: typeof AuthenticatedManagerHubRoute
  AuthenticatedProjectionsRoute: typeof AuthenticatedProjectionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedThisWeekRoute: typeof AuthenticatedThisWeekRoute
  AuthenticatedTradeDeskRoute: typeof AuthenticatedTradeDeskRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
  AuthenticatedWaiversRoute: typeof AuthenticatedWaiversRoute
  AuthenticatedLeagueLeagueIdRoute: typeof AuthenticatedLeagueLeagueIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedGamedayRoute: AuthenticatedGamedayRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedLineupCheckRoute: AuthenticatedLineupCheckRoute,
  AuthenticatedManagerHubRoute: AuthenticatedManagerHubRoute,
  AuthenticatedProjectionsRoute: AuthenticatedProjectionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedThisWeekRoute: AuthenticatedThisWeekRoute,
  AuthenticatedTradeDeskRoute: AuthenticatedTradeDeskRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
  AuthenticatedWaiversRoute: AuthenticatedWaiversRoute,
  AuthenticatedLeagueLeagueIdRoute: AuthenticatedLeagueLeagueIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronInactivesRoute: ApiPublicCronInactivesRoute,
  ApiPublicCronLiveScoringRoute: ApiPublicCronLiveScoringRoute,
  ApiPublicCronTradeValuesRoute: ApiPublicCronTradeValuesRoute,
  ApiPublicCronTradeValuesIrRoute: ApiPublicCronTradeValuesIrRoute,
  ApiPublicYahooCallbackRoute: ApiPublicYahooCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
